### ISSUE TITLE
打包出错！

### ISSUE THREAD

**Issue by Ethan9001** [beansoftapp/umeng-muti-channel-build-tool-java#1]
错误详情：
       invalid entry size(expected 16500 but got 16476bytes)

这是咋回事呀

**Comment by beansoft** [comment]
这个在主页里已经说明了:
已知问题

最新版Gradle打包出的APK不能被ZIP工具所识别, 会导致重新签名失败. 如果你遇到此问题:

方案1: 使用旧版gradle打包, classpath 'com.android.tools.build:gradle:2.2.0' 测试通过;

方案2: 改用瓦力界面版和瓦力打包方案, 地址: https://github.com/beansoftapp/wallegui 技术细节参考: https://github.com/Meituan-Dianping/walle
